# Project information
site_name: 'INFO 2602'
site_description: 'Course site for INFO 2602'
site_author: 'Nicholas Mendez'
site_url: 'https://nmendez.app/info2602'

# Repository
repo_name: 'uwidcit/info2602'
repo_url: 'https://github.com/uwidcit/info2602'

# Copyright
copyright: 'Copyright &copy; 2019 Nicholas Mendez'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'theme'
  palette:
    primary: 'Deep Purple'
    accent: 'Amber'
  font:
    text: 'Source Serif Pro'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.json'
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-154889698-2'
  - 'auto'

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - git-revision-date-localized


#PWA Config
use_directory_urls: false
scope: "./"
version: 1.0.0